server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

spring:
  jmx:
    default-domain: mogu_eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka